### ISSUE TITLE
Backup fails

### ISSUE THREAD

**Issue by rangoy** [meganz/MEGAcmd#54] opened 2018-05-31 06:45 UTC
Backup fails, possibly due to date calculating errors.

mega-backup -l says next backup is due in the 70s (Sun, 31 Jul 1977 11:25:01 +0100)

Start of mega-cmd-server:

``
[info: 13:40:01] Resuming session...
[debug: 13:40:02] actUponLogin login
[debug: 13:40:02] Login correct ...
[debug: 13:40:02] Session file: /home/backupagent/.megaCmd/session
[debug: 13:40:02] Syncs file: /home/backupagent/.megaCmd/syncs
[debug: 13:40:02] Backups file: /home/backupagent/.megaCmd/backups
[debug: 13:40:02] Excluded file: /home/backupagent/.megaCmd/excluded
[info: 13:40:02] Fetching nodes ...
[info: 13:40:02] Loaded sync: /home/backupagent/targets to /test
[debug: 13:40:02]  Fetch nodes correctly
[info: 13:40:02] Login complete as g***@***.com
[info: 13:40:02] Restablishing backups ...
[info: 13:40:02] Added backup: /home/backupagent/targets to /backuptargets
[debug: 13:40:02] Succesfully resumed backup: /home/backupagent/targets to /backuptargets
[debug: 13:40:02] Backups file: /home/backupagent/.megaCmd/backups
[info: 13:40:02] Listening to petitions ...
[API:err: 13:40:02] Invalid calculated NextStartTime
[debug: 13:40:02] 2 folders added or updated
[debug: 13:40:02] 2 files added or updated
``

``
[Initiating server in background. Log: /home/backupagent/.megaCmd/megacmdserver.log]
TAG   LOCALPATH      REMOT...TPATH          STATUS
4     /home...argets /backuptargets         FAILED
  Max Backups:   10
  Period:         "0 0 4 * * *"
  Next backup scheduled for: Sun, 31 Jul 1977 11:25:01 +0100
   -- CURRENT/LAST BACKUP --
  FILES UP/TOT     FOLDERS CREATED    PROGRESS
       0/0                0         0.00/0.00  B  0.00%
`` 

System:

Raspbian stretch, locale: EN_us

**Comment by polmr** [comment] 2018-05-31 08:06
Hi @rangoy , I can totally reproduce it in a Raspberry. It only happens in this architecture due to an overflow of a 32 bits integer. We will fix it asap, thanks for reporting.

**Comment by polmr** [comment] 2018-06-01 07:54
It should be fixed already. Just update MEGAcmd @rangoy

**Comment by rangoy** [comment] 2018-06-01 09:38
Thanks,

I've just installed the latest build from the webpage, and it works. Thanks a lot!

**Closed** 2018-09-27 09:29 UTC
